### ISSUE TITLE
Neden GO?

### ISSUE THREAD

**Issue by zeki-kadiroglu** [Furkan-Gulsen/golang-docs-turkce#1]
**Hocam Merhaba,** 
içeriğiniz çok güzel elinize sağlık. 
Reponuz inanılmaz denk geldi, daha dün `GO` mu öğrensem dediğim anda repo karşımı çıktı. 
Neden bunu öğrenmeliyim konusunda sorularım olacaktı. 
* `GO` nun markette yeri nedir? Şu ana kadar hep `Python` ile çalışmış biri olarak. `GO` nun marketteki yeri ve potansiyeli nedir? 
* `BigData` projelerinde bu dil sıkça kullanılıyor mu?
*  `Ağ yazılımı` projelerinde ne gibi katkı sağılıyor. ?

**Comment by Furkan-Gulsen** [comment]
Repoyu beğendiğine sevindim :) 

Go öğrenmek için birçok sebep var. Backend alanındaki en hızlı çalışan dillerin başında geliyor.

Go'nun market yeri gün geçtikçe artıyor. Google, Amazon gibi global şirketlerden tut, Getir Trendyol gibi Türkiyeden çıkmış startuplara kadar her yerde kullanılıyor.

Big data alanında kullanmadım ama Go'da olan paralel çalışma özelliği sayesinde Big Data alanında da kullanıldığını birkaç yerde okudum.
